name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0

      - name: sonarcloud scan
        uses: SonarSource/sonarcloud-github-action@v1.7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
